# This file was generated by GoReleaser. DO NOT EDIT.
cask "cdclint" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "82976cdd6fc4365625a6baa68d4d3d0838e656905c6528be691d03cff3585372"
      url "https://github.com/avison9/cdclint/releases/download/v#{version}/cdclint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6347adc559ecd208337ebec4bb6e23beffd7a1f6f13ef1a225b0ef7915862693"
      url "https://github.com/avison9/cdclint/releases/download/v#{version}/cdclint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dfc2ca074fd95e7ae85269cc55ba31a415922625c2cd36c2fee17efc6567b3a4"
      url "https://github.com/avison9/cdclint/releases/download/v#{version}/cdclint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dd7d992eb39b8e465be90b9cec95b58aba4d5856dded0393fe63912d21b0a75e"
      url "https://github.com/avison9/cdclint/releases/download/v#{version}/cdclint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cdclint"
  desc "Lint the contract between your database, your Debezium connector and your sink"
  homepage "https://github.com/avison9/cdclint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cdclint"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cdclint"]
    end
  end

  # No zap stanza required
end
