# This file was generated by GoReleaser. DO NOT EDIT.
cask "cdclint" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "38fa8f59e1f05559106608c060adb1056fd138bbc2e882a64495c8a54e501671"
      url "https://github.com/avison9/cdclint/releases/download/v#{version}/cdclint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "baf29380e7d29aac7bf62923bac6fbc1e7715e706531fcce564c4f2c51b50857"
      url "https://github.com/avison9/cdclint/releases/download/v#{version}/cdclint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "76c3dffe9db20ba4ae6a184a63cb4c21bb83da4e26109f1f3711b79ecf5a0ae1"
      url "https://github.com/avison9/cdclint/releases/download/v#{version}/cdclint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "97853d2aaca5ef91a1c2b21152e2f01634fe8af572b9c450241d530f1dbdd350"
      url "https://github.com/avison9/cdclint/releases/download/v#{version}/cdclint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cdclint"
  desc "Lint the contract between your database, your Debezium connector and your sink"
  homepage "https://github.com/avison9/cdclint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cdclint"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cdclint"]
    end
  end

  # No zap stanza required
end
