# This file was generated by GoReleaser. DO NOT EDIT.
cask "cdclint" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "41f4639a63010450cba8f4e4d6f28f932ad975935f40ec18cb9cc1441f2e2286"
      url "https://github.com/avison9/cdclint/releases/download/v#{version}/cdclint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f63ebef6eb3c0802ba8d6fb17cde83606ffef2222e555a45b202bed63d70b2fb"
      url "https://github.com/avison9/cdclint/releases/download/v#{version}/cdclint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7595c22a179b11ccfadbc40ba122466336864217f589833dc12dec21f6d2f0f1"
      url "https://github.com/avison9/cdclint/releases/download/v#{version}/cdclint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ab1d4c0246b5def5a9a4dbd10972d206e960f1ee60d1d803e6efe273c19cd0da"
      url "https://github.com/avison9/cdclint/releases/download/v#{version}/cdclint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cdclint"
  desc "Lint the contract between your database, your Debezium connector and your sink"
  homepage "https://github.com/avison9/cdclint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cdclint"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cdclint"]
    end
  end

  # No zap stanza required
end
